/**
 * Build-time script: scan public/images/gamePlay/ and generate src/data/imageManifest.js.
 *
 * Naming convention: (Acu|Comp)_(A|B|C)_(\d+).<ext>
 *   e.g. Acu_C_06.png, Comp_A_01.jpg
 *   Prefix: Acu → acusensus, Comp → competitor
 *   Letter: A → distracted, B → seatbelt, C → safe
 *
 * Run before dev/build (e.g. predev, prebuild) so new images are picked up.
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const GAMEPLAY_DIR = path.join(ROOT, 'public', 'images', 'gamePlay')
const OUT_FILE = path.join(ROOT, 'src', 'data', 'imageManifest.js')

const FILENAME_RE = /^(Acu|Comp)_([ABC])_(\d+)\.(jpg|jpeg|png|webp|gif)$/i

const PREFIX_TO_POOL = {
  Acu: 'acusensus',
  Comp: 'competitor',
}

const LETTER_TO_LABEL = {
  A: 'distracted',
  B: 'seatbelt',
  C: 'safe',
}

function parseFilename(filename) {
  const m = filename.match(FILENAME_RE)
  if (!m) return null
  const [, prefix, letter, , ext] = m
  const pool = PREFIX_TO_POOL[prefix]
  const label = LETTER_TO_LABEL[letter.toUpperCase()]
  if (!pool || !label) return null
  const id = path.basename(filename, path.extname(filename))
  const src = `/images/gamePlay/${filename}`
  return { id, src, label, pool }
}

function generateManifest() {
  if (!fs.existsSync(GAMEPLAY_DIR)) {
    fs.mkdirSync(GAMEPLAY_DIR, { recursive: true })
  }

  const files = fs.readdirSync(GAMEPLAY_DIR)
  const entries = files
    .map((f) => parseFilename(f))
    .filter(Boolean)
    .sort((a, b) => a.id.localeCompare(b.id))

  const manifestLines = entries
    .map((e) => `  { id: ${JSON.stringify(e.id)}, src: ${JSON.stringify(e.src)}, label: ${JSON.stringify(e.label)}, pool: ${JSON.stringify(e.pool)} },`)
    .join('\n')

  const content = `/**
 * Ground-truth manifest for all game images (auto-generated by scripts/generateImageManifest.js).
 *
 * Images live in public/images/gamePlay/ with naming: (Acu|Comp)_(A|B|C)_(\\d+).<ext>
 *   Acu/Comp → acusensus/competitor; A=distracted, B=seatbelt, C=safe.
 */

export const IMAGE_CATEGORIES = ['seatbelt', 'distracted', 'safe']

export const imageManifest = [
${manifestLines}
]

/** Acusensus pool images */
export const acusensusImages = imageManifest.filter((img) => img.pool === 'acusensus')

/** Competitor pool images */
export const competitorImages = imageManifest.filter((img) => img.pool === 'competitor')

/** O(1) lookup: imageId → correct label. Used by COMPLETE_GAME scoring. */
export const labelByImageId = Object.fromEntries(
  imageManifest.map((img) => [img.id, img.label])
)

/** O(1) lookup: imageId → full image entry { id, src, label, pool }. */
export const imageById = Object.fromEntries(
  imageManifest.map((img) => [img.id, img])
)
`

  fs.writeFileSync(OUT_FILE, content, 'utf8')
  console.log(`Wrote ${entries.length} image(s) to ${OUT_FILE}`)
}

generateManifest()
